#      ______                                       ______     __                  __
#     / ____/________  ____  ____  ____ ___  __  __/ ____/  __/ /__________ ______/ /_____  _____
#    / __/ / ___/ __ \/ __ \/ __ \/ __ `__ \/ / / / __/ | |/_/ __/ ___/ __ `/ ___/ __/ __ \/ ___/
#   / /___/ /__/ /_/ / / / / /_/ / / / / / / /_/ / /____>  </ /_/ /  / /_/ / /__/ /_/ /_/ / /
#  /_____/\___/\____/_/ /_/\____/_/ /_/ /_/\__, /_____/_/|_|\__/_/   \__,_/\___/\__/\____/_/
#                                         /____/

config-versin: 1.2